source 'git@github.com:lhs7248/binaryRepo.git'

platform :ios, '9.0'

target 'LSDemo_Example' do
#  pod 'LSDemo', :path => '../'
  pod 'LSSample','0.1.0'

  target 'LSDemo_Tests' do
    inherit! :search_paths

    
  end
end
